Add: Button component with styling and html
Logan1x/LibreUI pull request #7
Opened 2022-01-29 12:18 UTC by Logan1x

2022-01-29 13:07 UTC, thegeorgenikhil requested changes
` border-radius: 0.2rem;
  padding: 0.5rem;
  margin: 0.5rem;
  font-size: 1rem;
  font-weight: bold;
  border: none;
  cursor: pointer;`

Hey Kushal, it would be better it could  make a separate class .btn and add these repeating properties in both the buttons and add that .btn class tho those button elements
It would make it more reusable and easier to customize in future when you are adding more buttons

2022-01-29 13:20 UTC, thegeorgenikhil reviewed
Everything else look fine!✅

2022-01-29 18:15 UTC, Parul1999 commented on button/button.css
> +  color: white;
use css variable

2022-01-29 18:20 UTC, Parul1999 requested changes
Use CSS variables, instead of hard-coding the color code.

2022-01-30 04:25 UTC, Logan1x commented on button/button.css
> +  color: white;
Done, replaced with color variable :)

2022-01-30 04:26 UTC, merged

2022-01-30 04:26 UTC, Logan1x commented
Thanks Nikhil & Parul for your suggestions, merging this now :)